[project]
name = "coachbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.18"
dependencies = [
    "ipykernel>=6.29.5",
    "peppi-py>=0.8.0",
]
